name: Deploy to Render

# Trigger workflow on push to main branch
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Login to Render using API key
      - name: Render Login
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Logging in to Render..."
          # No direct CLI login needed; API key is used in deployment step

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t bostonhousepricing:latest .

      # Push Docker image to Render
      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Deploying Docker image to Render..."
          curl -X POST "https://api.render.com/deploy/srv-${RENDER_SERVICE_ID}" \
               -H "Authorization: Bearer ${RENDER_API_KEY}" \
               -H "Accept: application/json"
